services:
    oauth2_server.authorization_endpoint.form.factory:
        class: 'OAuth2Framework\Bundle\Server\CorePlugin\Form\FormFactory'
        arguments:
            - '@form.factory'
            - '%oauth2_server.authorization_endpoint.name%'
            - '%oauth2_server.authorization_endpoint.type%'
            - '%oauth2_server.authorization_endpoint.validation_groups%'

    oauth2_server.authorization_endpoint.form_type.default:
        class: 'OAuth2Framework\Bundle\Server\Form\Type\AuthorizationType'
        arguments:
            - '@translator'
        tags:
            - { name: 'form.type', alias: 'oauth2_server_authorization' }

    oauth2_server.authorization_endpoint.form_handler.default:
        class: 'OAuth2Framework\Bundle\Server\Form\Handler\AuthorizationFormHandler'
