services:
    oauth2_server.openid_connect.id_token.manager.default:
        class: 'OAuth2Framework\Bundle\Server\OpenIdConnectPlugin\Model\IdTokenManager'
        arguments:
            - '@jose.jwt_creator.openid_connect'
            - '@jose.jwt_loader.openid_connect'
            - '%oauth2_server.openid_connect.id_token.manager.issuer%'
            - '%oauth2_server.openid_connect.id_token.manager.signature_algorithm%'
            - '@oauth2_server.openid_connect.id_token.manager.signature_key_set'
            - '@oauth2_server.openid_connect.userinfo'
            - '@event_dispatcher'

    oauth2_server.client_manager.rule.id_token_encryption_algorithms:
        class: 'OAuth2Framework\Component\Server\Client\Rule\IdTokenEncryptionAlgorithmsRule'
        arguments:
            - '@oauth2_server.openid_connect.id_token.manager'
        tags:
            - { name: 'oauth2_server_client_manager_rule' }
