services:
    oauth2_server.openid_connect.metadata:
        class: 'OAuth2Framework\Bundle\Server\OpenIdConnectPlugin\Service\Metadata'
        arguments:
            - '@router'

    oauth2_server.openid_connect.metadata.controller:
        class: 'OAuth2Framework\Bundle\Server\OpenIdConnectPlugin\Controller\MetadataController'
        arguments:
            - '@oauth2_server.openid_connect.metadata'
