services:
    oauth2_server.authorization_factory.parameter_checker.manager:
        class: 'OAuth2Framework\Component\Server\Endpoint\Authorization\ParameterChecker\ParameterCheckerManager'
        arguments:
            - '@oauth2_server.exception.manager'

    oauth2_server.authorization_factory.parameter_checker.display:
        class: 'OAuth2Framework\Component\Server\Endpoint\Authorization\ParameterChecker\DisplayParameterChecker'
        tags:
            - { name: 'oauth2_server.parameter_checker' }

    oauth2_server.authorization_factory.parameter_checker.prompt:
        class: 'OAuth2Framework\Component\Server\Endpoint\Authorization\ParameterChecker\PromptParameterChecker'
        tags:
            - { name: 'oauth2_server.parameter_checker' }

    oauth2_server.authorization_factory.parameter_checker.response_type:
        class: 'OAuth2Framework\Component\Server\Endpoint\Authorization\ParameterChecker\ResponseTypeParameterChecker'
        tags:
            - { name: 'oauth2_server.parameter_checker' }

    oauth2_server.authorization_factory.parameter_checker.nonce:
        class: 'OAuth2Framework\Component\Server\Endpoint\Authorization\ParameterChecker\NonceParameterChecker'
        tags:
            - { name: 'oauth2_server.parameter_checker' }

    oauth2_server.authorization_factory.parameter_checker.state:
        class: 'OAuth2Framework\Component\Server\Endpoint\Authorization\ParameterChecker\StateParameterChecker'
        tags:
            - { name: 'oauth2_server.parameter_checker' }
        arguments:
            - '%oauth2_server.authorization_endpoint.option.enforce_state%'

    oauth2_server.authorization_factory.parameter_checker.scope:
        class: 'OAuth2Framework\Component\Server\Endpoint\Authorization\ParameterChecker\ScopeParameterChecker'
        tags:
            - { name: 'oauth2_server.parameter_checker' }
        arguments:
            - '@oauth2_server.scope_manager'

    oauth2_server.authorization_factory.parameter_checker.redirect_uri:
        class: 'OAuth2Framework\Component\Server\Endpoint\Authorization\ParameterChecker\RedirectUriParameterChecker'
        tags:
            - { name: 'oauth2_server.parameter_checker' }
        arguments:
            - '%oauth2_server.authorization_endpoint.option.enforce_secured_redirect_uri%'
            - '%oauth2_server.authorization_endpoint.option.enforce_redirect_uri_storage%'

    oauth2_server.authorization_factory.parameter_checker.response_mode:
        class: 'OAuth2Framework\Component\Server\Endpoint\Authorization\ParameterChecker\ResponseModeParameterChecker'
        tags:
            - { name: 'oauth2_server.parameter_checker' }
        arguments:
            - '%oauth2_server.authorization_endpoint.option.allow_response_mode_parameter%'
