services:
    oauth2_server.jwt_access_token.manager:
        class: 'OAuth2Framework\Bundle\Server\JWTAccessTokenPlugin\Model\JWTAccessTokenManager'
        arguments:
            - '@jose.jwt_creator.jwt_access_token'
            - '@jose.jwt_loader.jwt_access_token'
            - '%oauth2_server.jwt_access_token.manager.signature_algorithm%'
            - '@oauth2_server.jwt_access_token.manager.signature_key_set'
            - '%oauth2_server.jwt_access_token.manager.key_encryption_algorithm%'
            - '%oauth2_server.jwt_access_token.manager.content_encryption_algorithm%'
            - '@oauth2_server.jwt_access_token.manager.key_encryption_key_set'
            - '%oauth2_server.jwt_access_token.manager.issuer%'
            - '@event_dispatcher'
        tags:
            - { name: 'oauth2_server.cleaner' }
