cache_dir: "/cache/gitsplit"

splits:
    - prefix: "src/Component/Core"
      target: "https://${GH_TOKEN}@github.com/oauth2-framework/oauth2-core.git"
    - prefix: "src/Bundle/JoseFramework"
      target: "https://${GH_TOKEN}@github.com/oauth2-framework/oauth2-bundle.git"

origins:
    - ^master$
    - ^v\d+\.\d+$
    - ^v\d+\.\d+\.\d+$