cache_dir: "/cache/gitsplit"

splits:
    - prefix: "src/Bundle"
      target: "https://${GH_TOKEN}@github.com/oauth2-framework/bundle.git"
    - prefix: "src/Component/AuthorizationCodeGrant"
      target: "https://${GH_TOKEN}@github.com/oauth2-framework/authorization-code-grant.git"
    - prefix: "src/Component/AuthorizationEndpoint"
      target: "https://${GH_TOKEN}@github.com/oauth2-framework/authorization-endpoint.git"
    - prefix: "src/Component/BearerTokenType"
      target: "https://${GH_TOKEN}@github.com/oauth2-framework/bearer-token.git"
    - prefix: "src/Component/ClientAuthentication"
      target: "https://${GH_TOKEN}@github.com/oauth2-framework/client-authentication.git"
    - prefix: "src/Component/ClientConfigurationEndpoint"
      target: "https://${GH_TOKEN}@github.com/oauth2-framework/client-configuration-endpoint.git"
    - prefix: "src/Component/ClientCredentialsGrant"
      target: "https://${GH_TOKEN}@github.com/oauth2-framework/client-credentials-grant.git"
    - prefix: "src/Component/ClientRegistrationEndpoint"
      target: "https://${GH_TOKEN}@github.com/oauth2-framework/client-registration-endpoint.git"
    - prefix: "src/Component/ClientRule"
      target: "https://${GH_TOKEN}@github.com/oauth2-framework/client-rule.git"
    - prefix: "src/Component/Core"
      target: "https://${GH_TOKEN}@github.com/oauth2-framework/core.git"
    - prefix: "src/Component/ImplicitGrant"
      target: "https://${GH_TOKEN}@github.com/oauth2-framework/implicit-grant.git"
    - prefix: "src/Component/IssuerDiscoveryEndpoint"
      target: "https://${GH_TOKEN}@github.com/oauth2-framework/issuer-discovery-endpoint.git"
    - prefix: "src/Component/JwtBearerGrant"
      target: "https://${GH_TOKEN}@github.com/oauth2-framework/jwt-bearer-grant.git"
    - prefix: "src/Component/MacTokenType"
      target: "https://${GH_TOKEN}@github.com/oauth2-framework/mac-token-type.git"
    - prefix: "src/Component/MetadataEndpoint"
      target: "https://${GH_TOKEN}@github.com/oauth2-framework/metadata-endpoint.git"
    - prefix: "src/Component/NoneGrant"
      target: "https://${GH_TOKEN}@github.com/oauth2-framework/none-grant.git"
    - prefix: "src/Component/OpenIdConnect"
      target: "https://${GH_TOKEN}@github.com/oauth2-framework/openid-connect.git"
    - prefix: "src/Component/RefreshTokenGrant"
      target: "https://${GH_TOKEN}@github.com/oauth2-framework/refresh-token-grant.git"
    - prefix: "src/Component/ResourceOwnerPasswordCredentialsGrant"
      target: "https://${GH_TOKEN}@github.com/oauth2-framework/resource-owner-password-credentials-grant.git"
    - prefix: "src/Component/Scope"
      target: "https://${GH_TOKEN}@github.com/oauth2-framework/scope.git"
    - prefix: "src/Component/TokenEndpoint"
      target: "https://${GH_TOKEN}@github.com/oauth2-framework/token-endpoint.git"
    - prefix: "src/Component/TokenIntrospectionEndpoint"
      target: "https://${GH_TOKEN}@github.com/oauth2-framework/token-introspection-endpoint.git"
    - prefix: "src/Component/TokenRevocationEndpoint"
      target: "https://${GH_TOKEN}@github.com/oauth2-framework/token-revocation-endpoint.git"
    - prefix: "src/Component/TokenType"
      target: "https://${GH_TOKEN}@github.com/oauth2-framework/token-type.git"


origins:
    - ^master$
    - ^v\d+\.\d+$
    - ^v\d+\.\d+\.\d+$
