language: php

sudo: false

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
    - php: hhvm
  include:
    - php: 7.0
    - php: 7.0
      env: deps=low
    - php: 7.1
    - php: hhvm
    - php: nightly
    - php: nightly
      env: deps=low

services:
    - memcached

before_script:
  # we remove xdebug support (not needed)
  - phpenv config-rm xdebug.ini || true

  # we add memcached extension
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;'

  # prepare composer and dependencies
  - composer self-update
  - if [[ $deps = low ]]; then composer update --no-interaction --prefer-lowest; fi
  - if [[ !$deps ]]; then composer install --no-interaction ; fi

script:
    - vendor/bin/behat -v
