language: php

sudo: false

php:
    - 5.5
    - 5.6
    - 7
    - hhvm
    - nightly

before_script:
    - composer install --no-interaction
    - mkdir -p build/logs

script:
    - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
    - vendor/bin/coveralls --no-interaction
