OAuth2Framework\Component\RefreshTokenGrant\AbstractRefreshToken:
    type: mappedSuperclass
    fields:
        accessTokenIds:
            type: array
        expiresAt:
            type: date_immutable
        resourceOwnerId:
            type: resource_owner_id
        clientId:
            type: client_id
        parameter:
            type: databag
        metadata:
            type: databag
        revoked:
            type: boolean
        resourceServerId:
            type: resource_server_id
            nullable: true
