OAuth2Framework\Component\Core\Client\AbstractClient:
    type: mappedSuperclass
    fields:
        ownerId:
            type: resource_owner_id
            nullable: true
        parameter:
            type: databag
        deleted:
            type: boolean
